name: DataMiner CICD NuGet Solution

on:
  push:
    branches: []
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  workflow_dispatch:

jobs:
  CICD:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/NuGet Solution Master Workflow.yml@main
    with:
      sonarCloudProjectName: SkylineCommunications_Skyline.DataMiner.CICD.Parsers
    secrets:
      nugetApiKey: ${{ secrets.NUGETAPIKEY }}

  Tests-Ubuntu:
    runs-on: ubuntu-22.04 # Latest misses mono for .NET Framework
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Test
        run: dotnet test -c Release
